### ISSUE TITLE
Errors trying build

### ISSUE THREAD

**Issue by eriknyk** [inversify/inversify-hapi-example#5]
```
$ gulp build

[17:06:56] Using gulpfile ~/Sandbox/inversify-hapi-example/gulpfile.js
[17:06:56] Starting 'tslint'...
[17:06:56] Starting 'compile'...
TypeScript  Version 2.5.3

[17:06:58] Finished 'tslint' after 1.05 s
src/configs/configurations.ts(10,21): error TS2304: Cannot find name 'process'.
src/configs/configurations.ts(11,24): error TS2304: Cannot find name 'require'.
src/index.ts(3,35): error TS2304: Cannot find name 'process'.
src/libs/ioc/index.ts(4,13): error TS2304: Cannot find name 'process'.
src/libs/ioc/index.ts(8,1): error TS2304: Cannot find name 'require'.
src/libs/ioc/inversify.dev.config.ts(1,10): error TS2305: Module '"/Users/erik/Sandbox/inversify-hapi-example/node_modules/inversify/dts/inversify"' has no exported member 'IKernel'.
src/libs/ioc/inversify.test.config.ts(1,10): error TS2305: Module '"/Users/erik/Sandbox/inversify-hapi-example/node_modules/inversify/dts/inversify"' has no exported member 'IKernel'.
src/libs/plugins/logger/index.ts(10,31): error TS2304: Cannot find name 'require'.
src/libs/plugins/logger/index.ts(16,27): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(8,17): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(9,17): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(11,31): error TS2304: Cannot find name 'require'.
src/server.ts(11,14): error TS2304: Cannot find name 'process'.
src/server.ts(22,21): error TS2304: Cannot find name '__dirname'.
src/server.ts(26,28): error TS2304: Cannot find name 'require'.
test/repository/memory/taskRepositoryTests.ts(9,1): error TS2304: Cannot find name 'describe'.
test/repository/memory/taskRepositoryTests.ts(10,3): error TS2304: Cannot find name 'it'.
test/repository/mongo/taskRepositoryTests.ts(13,1): error TS2304: Cannot find name 'describe'.
test/repository/mongo/taskRepositoryTests.ts(14,3): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(10,1): error TS2304: Cannot find name 'describe'.
test/server/taskControllerTests.ts(11,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(18,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(36,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(43,5): error TS2304: Cannot find name 'it'.
typings.d.ts(1,22): error TS6053: File '/Users/erik/Sandbox/inversify-hapi-example/typings/main.d.ts' not found.
typings.d.ts(2,22): error TS6053: File '/Users/erik/Sandbox/inversify-hapi-example/node_modules/inversify/type_definitions/inversify/inversify.d.ts' not found.

[17:06:59] 'compile' errored after 2.46 s
[17:06:59] Error: Command failed: tsc

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

**Comment by remojansen** [comment]
Hi, the hapijs example is the only one that is not maintained by the core inversifyjs team. If you manage to fix it and you want to contribute a fix that would be awesome but it is likely to be hard because it is very outdated

**Comment by remojansen** [comment]
I'm closing the issue because it should be reported in the core repo https://github.com/inversify/InversifyJS/issues
